apiVersion: v1
kind: Service
metadata:
  name: go-ws-kafka-ui-service
spec:
  selector:
    app: go-ws-kafka-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: go-ws-kafka-service
spec:
  selector:
    app: go-ws-kafka
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
#  type: NodePort