apiVersion: v1
kind: Service
metadata:
  name: go-ws-kafka-ui-service
spec:
  type: NodePort
  selector:
    app: go-ws-kafka-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: go-ws-kafka-service
spec:
  type: ClusterIP
  selector:
    app: go-ws-kafka
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
